#!/usr/bin/perl

while (<DATA>) {
    my @fields = split /\t/;
    s/\s+$//g for @fields;
    my $distro = shift @fields;
    my $desc = shift @fields;
    $distro =~ s/-[^-]*$//;
    print qq{* "$distro"<http://search.cpan.org/dist/$distro>: $desc\n};
}

# This data is just a cut & paste from http://search.cpan.org/~petdance
__DATA__
ack-1.52  	grep-like text finder  	[Download] [Browse]  	21 Dec 2006
Acme-PM-Chicago-0.01 	Functions useful for the Chicago.pm group 	[Download] [Browse] 	06 Jan 2004
Apache-Lint-0.10 	Apache wrapper around HTML::Lint 	[Download] [Browse] 	22 Nov 2004
Apache-Pod-0.22 	base class for converting Pod files to prettier forms 	[Download] [Browse] 	16 Sep 2005
Carp-Assert-More-1.12 	convenience wrappers around Carp::Assert 	[Download] [Browse] 	14 Oct 2005
Data-Hash-Totals-0.10 	Handle hashes that are totals or counts 	[Download] [Browse] 	17 Nov 2004
File-Find-Wanted-0.01 	More obvious wrapper around File::Find 	[Download] [Browse] 	05 Aug 2004
File-Next-0.36 	File-finding iterator 	[Download] [Browse] 	21 Dec 2006
fluff-0.01 	  	[Download] [Browse] 	08 Mar 2006
HTML-Lint-2.02 	check for HTML errors in a string or file 	[Download] [Browse] 	03 Nov 2005
HTML-Tagset-3.10 	data tables useful in parsing HTML 	[Download] [Browse] 	08 Nov 2005
HTML-Tidy-1.07_01 	(X)HTML validation in a Perl object 	[Download] [Browse] 	10 Nov 2006
HTML-Tree-3.20 	overview of HTML::TreeBuilder et al 	[Download] [Browse] 	04 Jun 2006
hwd-0.21_01 	The How We Doin'? project tracking tool 	[Download] [Browse] 	29 May 2006
List-Cycle-0.04 	Objects for cycling through a list of values 	[Download] [Browse] 	10 Nov 2005
Locale-Maketext-1.10 	framework for localization 	[Download] [Browse] 	10 Nov 2005
MARC-Record-1.39_02 	Perl extension for handling MARC records 	[Download] [Browse] 	21 Dec 2004
Module-Depends-Tree-1.00 	A container for functions for the deptree program 	[Download] [Browse] 	23 Nov 2006
Module-Starter-1.42 	a simple starter kit for any module 	[Download] [Browse] 	09 Nov 2005
Perl-Critic-Bangs-0.22 	A collection of handy Perl::Critic policies 	[Download] [Browse] 	16 Jul 2006
Pod-Outline-0.10 	For generating outlines of POD files 	[Download] [Browse] 	02 Jan 2005
TAP-1.00 	The Test Anything Protocal 	[Download] [Browse] 	29 Jun 2006
Template-Timer-0.04 	Rudimentary profiling for Template Toolkit 	[Download] [Browse] 	16 Oct 2005
Test-Harness-2.64 	Run Perl standard test scripts with statistics 	[Download] [Browse] 	06 Oct 2006
Test-HTML-Tidy-1.00 	Test::More-style wrapper around HTML::Tidy 	[Download] [Browse] 	26 Feb 2004
Test-Memory-Cycle-1.04 	Check for memory leaks and circular memory references 	[Download] [Browse] 	06 Aug 2006
Test-Pod-1.26 	check for POD errors in files 	[Download] [Browse] 	19 Jul 2006
Test-Pod-Coverage-1.08 	Check for pod coverage in your distribution. 	[Download] [Browse] 	25 Jan 2006
Test-Program-0.04 	Testing tools for Perl programs 	[Download] [Browse] 	23 Mar 2006
Test-Taint-1.04 	Tools to test taintedness 	[Download] [Browse] 	09 Aug 2004
Test-WWW-Mechanize-1.12 	Testing-specific WWW::Mechanize subclass 	[Download] [Browse] 	06 Jul 2006
WDDX-1.02 	Module for reading and writing WDDX packets 	[Download] [Browse] 	01 Dec 2003
WWW-Mechanize-1.21_04 	Handy web browsing in a Perl object 	[Download] [Browse] 	07 Oct 2006
WWW-Mechanize-Cached-1.32 	Cache response to be polite 	[Download] [Browse] 	11 Apr 2004
