#!/usr/bin/ruby

=begin rdoc

http://projecteuler.net/index.php?section=problems&id=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.

=end

fibs = [1, 2]

while ( fibs[-1] < 4_000_000 )
    fibs << fibs[-1] + fibs[-2]
end

sum = 0
fibs.each { |i| sum += i if i % 2 == 0 and i < 4_000_000 }

print sum, "\n"
