#!/usr/bin/python

"""

https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms
will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do
not exceed four million, find the sum of the even-valued terms.

"""

sum = 0
fibs = [1, 1]
while fibs[-1] < 4000000:
    n = fibs[-2] + fibs[-1]
    fibs.append(n)
    if (n % 2 == 0):
        sum += n

print(sum)
